# Generated by Django 6.0.4 on 2026-05-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialMoodle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(help_text='DNI o Usuario de Moodle', max_length=50, unique=True)),
                ('contrasena', models.CharField(help_text='Contraseña de Moodle', max_length=255)),
                ('esta_activa', models.BooleanField(default=True, help_text='Indica si el bot debe usar esta cuenta')),
                ('ultima_conexion', models.DateTimeField(blank=True, help_text='Última vez que el bot entró con éxito', null=True)),
            ],
            options={
                'verbose_name': 'Credencial de Moodle',
                'verbose_name_plural': 'Credenciales de Moodle',
            },
        ),
    ]
