# Generated by Django 6.0.4 on 2026-05-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaAutomatizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_nombre', models.CharField(help_text='Nombre exacto del curso. Ej: DISEÑO WEB', max_length=255)),
                ('titulo_general', models.CharField(default='Cronograma general de clases', help_text='Texto a poner en la sección General', max_length=255)),
                ('mensaje_avisos', models.CharField(default='¡Bienvenidos! Es vital cumplir con las tareas.', help_text='Texto motivador para Avisos', max_length=255)),
                ('esta_activa', models.BooleanField(default=True, help_text='Indica si el bot debe procesar este curso')),
                ('ultima_ejecucion', models.DateTimeField(blank=True, help_text='Última vez que se automatizó', null=True)),
            ],
            options={
                'verbose_name': 'Tarea de Automatización',
                'verbose_name_plural': 'Tareas de Automatización',
            },
        ),
    ]
