# Generated by Django 6.0.4 on 2026-05-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0002_tareaautomatizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaautomatizacion',
            name='texto_recurso_s1',
            field=models.TextField(blank=True, default='Lee atentamente los materiales...', help_text='Contenido del Área de texto', null=True),
        ),
        migrations.AddField(
            model_name='tareaautomatizacion',
            name='titulo_recurso_s1',
            field=models.CharField(blank=True, default='Instrucciones de la semana', help_text='Título del Área de texto en Semana 1', max_length=255, null=True),
        ),
    ]
