# Generated by Django 6.0.4 on 2026-05-03 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0003_tareaautomatizacion_texto_recurso_s1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareaautomatizacion',
            name='texto_recurso_s1',
        ),
        migrations.RemoveField(
            model_name='tareaautomatizacion',
            name='titulo_recurso_s1',
        ),
        migrations.CreateModel(
            name='RecursoSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_numero', models.PositiveIntegerField(help_text='Número de la semana (1, 2, 3...)')),
                ('titulo', models.CharField(help_text='Título del Área de texto', max_length=255)),
                ('texto', models.TextField(help_text='Contenido detallado para esta semana')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_semanas', to='moodle.tareaautomatizacion')),
            ],
            options={
                'verbose_name': 'Recurso de Semana',
                'verbose_name_plural': 'Recursos por Semana',
                'ordering': ['semana_numero'],
            },
        ),
    ]
