# Generated by Django 6.0.4 on 2026-05-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0004_remove_tareaautomatizacion_texto_recurso_s1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursosemana',
            name='ruta_archivo_desarrollo',
            field=models.CharField(blank=True, help_text="Ruta absoluta al archivo a subir en 'Desarrollo de clase'. Ej: C:\\Users\\...\\archivo.pdf", max_length=500, null=True),
        ),
    ]
