# Generated by Django 6.0.4 on 2026-05-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0005_recursosemana_ruta_archivo_desarrollo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recursosemana',
            name='ruta_archivo_desarrollo',
        ),
        migrations.AddField(
            model_name='recursosemana',
            name='archivos_carpetas',
            field=models.JSONField(blank=True, help_text='Rutas de archivos por carpeta en formato JSON. Ejemplo: {"desarrollo": "C:\\\\ruta\\\\archivo.pdf", "analisis": "C:\\\\ruta\\\\otro.pdf", "evaluacion": "C:\\\\ruta\\\\tercero.pdf"}', null=True),
        ),
    ]
